os: osx
osx_image: xcode10.2
install: pipenv --three install --deploy --dev
addons:
  homebrew:
    packages:
      - pandoc
      - pipenv
      - wkhtmltopdf
    update: true
script: ./scripts/build
after_success: ./scripts/build_docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: site
  on:
    branch: master