os: osx
osx_image: xcode10.2
addons:
  homebrew:
    packages:
      - pandoc
      - pipenv
    casks:
      - wkhtmltopdf
    update: true
install: ./script/install
script: ./script/build
after_success: ./script/build_docs
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  local_dir: site
  on:
    branch: master