site_author: Ryan Balfanz
site_description: Resume of Ryan Balfanz resume in various formats
site_name: RyanBalfanz/resume-proof-of-concept
site_url: https://ryanbalfanz.github.io/resume-proof-of-concept/

repo_name: ryanbalfanz/resume-proof-of-concept
repo_url: https://github.com/ryanbalfanz/resume-proof-of-concept

theme:
  name: 'material'
  include_sidebar: false

nav:
  - Downloads: 'index.md'
  - PDF: 'static/balfanz_resume.pdf'
  - DOCX: 'static/balfanz_resume.docx'
